# Generated by Django 5.2.7 on 2026-07-09 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MigrationIntakeSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "migration_request_id",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("requested_date", models.CharField(max_length=64)),
                ("requestor", models.CharField(max_length=128)),
                ("status", models.CharField(default="new", max_length=32)),
                ("project_name", models.CharField(max_length=255)),
                ("migration_type", models.CharField(max_length=128)),
                ("migration_type_value", models.CharField(max_length=64)),
                ("region", models.CharField(max_length=16)),
                ("supporting_gsc_sites_custom", models.BooleanField(default=False)),
                ("custom_supporting_justification", models.TextField(blank=True)),
                (
                    "custom_approval_file_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "custom_approval_file_size",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "custom_approval_file_type",
                    models.CharField(blank=True, max_length=128),
                ),
                ("function_name", models.CharField(max_length=255)),
                ("proposed_scope", models.TextField()),
                ("fte_number", models.CharField(max_length=8)),
                ("jl2", models.CharField(default="0", max_length=8)),
                ("jl3", models.CharField(default="0", max_length=8)),
                ("jl4", models.CharField(default="0", max_length=8)),
                ("job_level_total", models.PositiveSmallIntegerField(default=0)),
                ("risks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "migration_intake_submission",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MigrationIntakeProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=255)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="api.migrationintakesubmission",
                    ),
                ),
            ],
            options={
                "db_table": "migration_intake_product",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("submission", "product"), name="uniq_submission_product"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MigrationIntakeLocationStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_strategy", models.CharField(max_length=16)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_strategies",
                        to="api.migrationintakesubmission",
                    ),
                ),
            ],
            options={
                "db_table": "migration_intake_location_strategy",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("submission", "location_strategy"),
                        name="uniq_submission_location_strategy",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MigrationIntakeLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=128)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="api.migrationintakesubmission",
                    ),
                ),
            ],
            options={
                "db_table": "migration_intake_language",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("submission", "language"),
                        name="uniq_submission_language",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MigrationIntakeGscSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(max_length=64)),
                (
                    "site_type",
                    models.CharField(
                        choices=[("default", "Default"), ("custom", "Custom")],
                        max_length=16,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gsc_sites",
                        to="api.migrationintakesubmission",
                    ),
                ),
            ],
            options={
                "db_table": "migration_intake_gsc_site",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("submission", "site_name", "site_type"),
                        name="uniq_submission_gsc_site",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MigrationIntakeCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=128)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="countries",
                        to="api.migrationintakesubmission",
                    ),
                ),
            ],
            options={
                "db_table": "migration_intake_country",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("submission", "country"), name="uniq_submission_country"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MigrationIntakeAreaLocationPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(max_length=64)),
                ("location_strategy", models.CharField(max_length=16)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_location_pairs",
                        to="api.migrationintakesubmission",
                    ),
                ),
            ],
            options={
                "db_table": "migration_intake_area_location_pair",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("submission", "area", "location_strategy"),
                        name="uniq_submission_area_location_pair",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MigrationIntakeAreaCountryPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(max_length=64)),
                ("country", models.CharField(max_length=128)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_country_pairs",
                        to="api.migrationintakesubmission",
                    ),
                ),
            ],
            options={
                "db_table": "migration_intake_area_country_pair",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("submission", "area", "country"),
                        name="uniq_submission_area_country_pair",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MigrationIntakeArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(max_length=64)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="api.migrationintakesubmission",
                    ),
                ),
            ],
            options={
                "db_table": "migration_intake_area",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("submission", "area"), name="uniq_submission_area"
                    )
                ],
            },
        ),
    ]
