# Generated by Django 5.2.7 on 2026-07-09 05:18

from django.db import migrations, models


def copy_related_rows_into_submission(apps, schema_editor):
    Submission = apps.get_model("api", "MigrationIntakeSubmission")
    Area = apps.get_model("api", "MigrationIntakeArea")
    Country = apps.get_model("api", "MigrationIntakeCountry")
    LocationStrategy = apps.get_model("api", "MigrationIntakeLocationStrategy")
    AreaLocationPair = apps.get_model("api", "MigrationIntakeAreaLocationPair")
    AreaCountryPair = apps.get_model("api", "MigrationIntakeAreaCountryPair")
    GscSite = apps.get_model("api", "MigrationIntakeGscSite")
    Product = apps.get_model("api", "MigrationIntakeProduct")
    Language = apps.get_model("api", "MigrationIntakeLanguage")

    for submission_id in Submission.objects.values_list("pk", flat=True):
        areas = list(
            Area.objects.filter(submission_id=submission_id)
            .order_by("id")
            .values_list("area", flat=True)
        )
        countries = list(
            Country.objects.filter(submission_id=submission_id)
            .order_by("id")
            .values_list("country", flat=True)
        )
        location_strategies = list(
            LocationStrategy.objects.filter(submission_id=submission_id)
            .order_by("id")
            .values_list("location_strategy", flat=True)
        )
        area_location_pairs = [
            {"area": row.area, "locationStrategy": row.location_strategy}
            for row in AreaLocationPair.objects.filter(
                submission_id=submission_id
            ).order_by("id")
        ]
        area_country_pairs = [
            {"area": row.area, "country": row.country}
            for row in AreaCountryPair.objects.filter(
                submission_id=submission_id
            ).order_by("id")
        ]
        default_supporting_gsc_sites = list(
            GscSite.objects.filter(
                submission_id=submission_id, site_type="default"
            ).values_list("site_name", flat=True)
        )
        custom_supporting_gsc_sites = list(
            GscSite.objects.filter(
                submission_id=submission_id, site_type="custom"
            ).values_list("site_name", flat=True)
        )
        products = list(
            Product.objects.filter(submission_id=submission_id)
            .order_by("id")
            .values_list("product", flat=True)
        )
        language_dependencies = list(
            Language.objects.filter(submission_id=submission_id)
            .order_by("id")
            .values_list("language", flat=True)
        )
        Submission.objects.filter(pk=submission_id).update(
            areas=areas,
            countries=countries,
            location_strategies=location_strategies,
            area_location_pairs=area_location_pairs,
            area_country_pairs=area_country_pairs,
            default_supporting_gsc_sites=default_supporting_gsc_sites,
            custom_supporting_gsc_sites=custom_supporting_gsc_sites,
            products=products,
            language_dependencies=language_dependencies,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="migrationintakesubmission",
            name="area_country_pairs",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="migrationintakesubmission",
            name="area_location_pairs",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="migrationintakesubmission",
            name="areas",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="migrationintakesubmission",
            name="countries",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="migrationintakesubmission",
            name="custom_supporting_gsc_sites",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="migrationintakesubmission",
            name="default_supporting_gsc_sites",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="migrationintakesubmission",
            name="language_dependencies",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="migrationintakesubmission",
            name="location_strategies",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="migrationintakesubmission",
            name="products",
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(
            copy_related_rows_into_submission,
            migrations.RunPython.noop,
        ),
        migrations.DeleteModel(
            name="MigrationIntakeArea",
        ),
        migrations.DeleteModel(
            name="MigrationIntakeAreaCountryPair",
        ),
        migrations.DeleteModel(
            name="MigrationIntakeAreaLocationPair",
        ),
        migrations.DeleteModel(
            name="MigrationIntakeCountry",
        ),
        migrations.DeleteModel(
            name="MigrationIntakeGscSite",
        ),
        migrations.DeleteModel(
            name="MigrationIntakeLanguage",
        ),
        migrations.DeleteModel(
            name="MigrationIntakeLocationStrategy",
        ),
        migrations.DeleteModel(
            name="MigrationIntakeProduct",
        ),
    ]
