# Generated by Django 5.2.7 on 2026-07-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_location_strategy_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="FpoMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("l1", models.CharField(blank=True, default="", max_length=128)),
                ("gpl", models.CharField(blank=True, default="", max_length=64)),
                ("l2", models.CharField(blank=True, default="", max_length=128)),
                ("sfpo", models.CharField(blank=True, default="", max_length=128)),
                (
                    "num_business_policy",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("l3", models.CharField(blank=True, default="", max_length=128)),
                ("fpo", models.CharField(blank=True, default="", max_length=255)),
                ("risk_link", models.TextField(blank=True, default="")),
                ("control_link", models.TextField(blank=True, default="")),
                ("l4", models.CharField(blank=True, default="", max_length=255)),
                (
                    "activity_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "sub_process_call_activity",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "activity_type_2",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "assigned_models_from_l5",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "process_level",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "process_grouping",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "last_change",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "guid",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("connect_link", models.TextField(blank=True, default="")),
                (
                    "num_automated_activities",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "num_system_supported_activities",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "num_manual_activities",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "num_undefined_activities",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "num_sub_process_activities",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "num_ms_office_activities",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "num_touchpoint_external_parties",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("num_risks", models.CharField(blank=True, default="", max_length=16)),
                (
                    "num_controls",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "num_manual_controls",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "num_business_rules",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "report_generation_date",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("sharepoint_link_sop", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "fpo_mapping",
                "indexes": [
                    models.Index(
                        fields=["l1", "l2", "l3"], name="fpo_mapping_l1_8a6a84_idx"
                    ),
                    models.Index(fields=["fpo"], name="fpo_mapping_fpo_e12ba5_idx"),
                    models.Index(fields=["sfpo"], name="fpo_mapping_sfpo_efe8de_idx"),
                ],
            },
        ),
    ]
