# Generated by Django 5.2.15 on 2026-07-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_gsc_site_mapping"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="gscsitemapping",
            new_name="gsc_site_ma_region_5b7743_idx",
            old_name="gsc_site_ma_region_8a2c1f_idx",
        ),
        migrations.RenameIndex(
            model_name="opportunityassessment",
            new_name="opportunity_migrati_ec5253_idx",
            old_name="opportunity_migrati_idx",
        ),
        migrations.RenameIndex(
            model_name="productownership",
            new_name="product_own_product_4e8731_idx",
            old_name="product_own_product_7c9f2a_idx",
        ),
        migrations.RenameIndex(
            model_name="productownership",
            new_name="product_own_manager_5530e9_idx",
            old_name="product_own_manager_4e1b8d_idx",
        ),
        migrations.AddField(
            model_name="opportunityassessment",
            name="location",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="opportunityassessment",
            name="product",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
