# Generated by Django 5.2.16 on 2026-08-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_project_attributes_access_migration_intake'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productownership',
            new_name='product_own_region_3441b8_idx',
            old_name='product_own_region_5f2a1c_idx',
        ),
        migrations.RenameIndex(
            model_name='productownership',
            new_name='product_own_migrati_b86471_idx',
            old_name='product_own_migrati_8d4b2e_idx',
        ),
        migrations.RenameIndex(
            model_name='servicecatalogue',
            new_name='service_cat_product_a6a147_idx',
            old_name='service_cat_product_l123_idx',
        ),
        migrations.RenameIndex(
            model_name='servicecatalogue',
            new_name='service_cat_current_259719_idx',
            old_name='service_cat_ownership_idx',
        ),
        migrations.AlterField(
            model_name='projectganttplan',
            name='tasks',
            field=models.JSONField(default=list, help_text='[{id, name, plan:{startWeek,endWeek}, actual, completedAt, comments:[{id, at, text, fromPlan, toPlan}]}, ...]'),
        ),
    ]
