# Generated by Django 5.2.16 on 2026-08-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_rename_product_own_region_5f2a1c_idx_product_own_region_3441b8_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="migrationintakesubmission",
            name="business_case_submission_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
