# Generated by Django 5.2.16 on 2026-08-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_migrationintakesubmission_business_case_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectganttplan',
            name='tasks',
            field=models.JSONField(default=list, help_text='[{id, name, plan:{startWeek,endWeek}, actual, completedAt, comments:[{id, at, text, updatedBy, fromPlan, toPlan}]}, ...]'),
        ),
    ]
