# Generated by Django 5.2.16 on 2026-08-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_project_attributes_access_input_for_approval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovalInput',
        ),
        migrations.RemoveField(
            model_name='projectattributesaccess',
            name='input_for_approval',
        ),
        migrations.AlterField(
            model_name='productownership',
            name='migration_manager',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
