# Generated by Django 5.2.16 on 2026-08-25 06:37

import json
from pathlib import Path

from django.db import migrations, models


def seed_approval_input(apps, schema_editor):
    ApprovalInput = apps.get_model("api", "ApprovalInput")
    if ApprovalInput.objects.exists():
        return

    seed_path = Path(__file__).resolve().parent.parent / "data" / "approval_input_seed.json"
    if not seed_path.exists():
        return

    rows = json.loads(seed_path.read_text(encoding="utf-8"))
    ApprovalInput.objects.bulk_create(
        [
            ApprovalInput(
                activity_function=row.get("activity_function", ""),
                product=row.get("product", ""),
                area_head=row.get("area_head", ""),
                pmo=row.get("pmo", ""),
                bpm=row.get("bpm", ""),
                fbp=row.get("fbp", ""),
                wpm=row.get("wpm", ""),
                elt=row.get("elt", ""),
                gsc_head=row.get("gsc_head", ""),
            )
            for row in rows
            if isinstance(row, dict)
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_delete_approvalinput_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectattributesaccess',
            name='input_for_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productownership',
            name='migration_manager',
            field=models.CharField(blank=True, default='', help_text='Email address(es) of the migration manager(s). Comma-separate multiple emails.', max_length=255),
        ),
        migrations.CreateModel(
            name='ApprovalInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_function', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('product', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('area_head', models.CharField(blank=True, default='', help_text='Area Head email(s).', max_length=255)),
                ('pmo', models.CharField(blank=True, default='', help_text='PMO email(s).', max_length=255)),
                ('bpm', models.CharField(blank=True, default='', help_text='BPM email(s).', max_length=255)),
                ('fbp', models.CharField(blank=True, default='', help_text='FBP email(s).', max_length=255)),
                ('wpm', models.CharField(blank=True, default='', help_text='WPM email(s).', max_length=255)),
                ('elt', models.CharField(blank=True, default='', help_text='ELT email(s).', max_length=255)),
                ('gsc_head', models.CharField(blank=True, default='', help_text='GSC Head email(s).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'approval_input',
                'ordering': ['activity_function', 'product'],
                'indexes': [models.Index(fields=['activity_function', 'product'], name='approval_in_act_fun_idx')],
            },
        ),
        migrations.RunPython(seed_approval_input, migrations.RunPython.noop),
    ]
