# Generated by Django 5.2.15 on 2026-09-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_bpm_rofo_and_actual"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="bpmactual",
            new_name="bpm_actual_year_5f5bb2_idx",
            old_name="bpm_actual_year_onboarding_idx",
        ),
        migrations.RenameIndex(
            model_name="bpmactual",
            new_name="bpm_actual_project_2c0880_idx",
            old_name="bpm_actual_project_name_idx",
        ),
        migrations.RenameIndex(
            model_name="bpmrofo",
            new_name="bpm_rofo_year_854d9a_idx",
            old_name="bpm_rofo_year_onboarding_idx",
        ),
        migrations.RenameIndex(
            model_name="bpmrofo",
            new_name="bpm_rofo_project_3d0816_idx",
            old_name="bpm_rofo_project_name_idx",
        ),
        migrations.AddField(
            model_name="bpmactual",
            name="part_not_part_of_rofo",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="bpmactual",
            name="positions_to_be_offshored_in_gsc",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="bpmrofo",
            name="positions_to_be_offshored_in_gsc",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
