# Generated by Django 5.2.16 on 2026-09-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_executive_summary_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationintakesubmission',
            name='business_case_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='business_case/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='migrationintakesubmission',
            name='business_case_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='migrationintakesubmission',
            name='business_case_file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
