# Generated by Django 5.2.16 on 2026-09-09 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_migrationintakesubmission_business_case_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationIntakeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='intake_attachments/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=128)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.migrationintakesubmission')),
            ],
            options={
                'db_table': 'migration_intake_attachment',
                'ordering': ['id'],
            },
        ),
    ]
