# Generated by Django 5.2.16 on 2026-09-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_migrationintakeattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpmactual',
            name='country',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='bpmrofo',
            name='country',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
