# Generated by Django 5.2.16 on 2026-09-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_bpmactual_country_bpmrofo_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpmactual',
            name='bu',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bpmactual',
            name='cost_center',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bpmactual',
            name='frontline_staff_cost_per_fte',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='bpmactual',
            name='function',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='bpmactual',
            name='function_id_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bpmactual',
            name='gsc_site',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bpmactual',
            name='gsc_staff_cost_per_fte',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='bpmactual',
            name='pid',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bpmactual',
            name='positions_to_be_released_in_frontline',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bpmactual',
            name='status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='bpmrofo',
            name='bu',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bpmrofo',
            name='cost_center',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bpmrofo',
            name='frontline_staff_cost_per_fte',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='bpmrofo',
            name='function',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='bpmrofo',
            name='function_id_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bpmrofo',
            name='gsc_site',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bpmrofo',
            name='gsc_staff_cost_per_fte',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='bpmrofo',
            name='pid',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bpmrofo',
            name='positions_to_be_released_in_frontline',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bpmrofo',
            name='status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
