# Generated by Django 5.2.16 on 2026-09-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_bpmactual_bu_bpmactual_cost_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpmactual',
            name='base_pids',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bpmactual',
            name='gsc1_leader',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bpmactual',
            name='gsc_leader',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bpmactual',
            name='project_cost',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='bpmactual',
            name='x_column',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='bpmrofo',
            name='base_pids',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bpmrofo',
            name='gsc1_leader',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bpmrofo',
            name='gsc_leader',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bpmrofo',
            name='part_not_part_of_rofo',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='bpmrofo',
            name='project_cost',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='bpmrofo',
            name='x_column',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
