# Generated by Django 5.2.16 on 2026-09-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_bpmactual_base_pids_bpmactual_gsc1_leader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpmactual',
            name='pid',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='bpmrofo',
            name='pid',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
