from django.core.management.base import BaseCommand

from api.models import MigrationIntakeSubmission


SAMPLE_SUBMISSIONS = [
    {
        "migration_request_id": "WPM_PRJ_20260615081234",
        "requested_date": "15 Jun 2026, 08:12:34",
        "requestor": "LYL114",
        "status": "new",
        "project_name": "APAC Ocean Consolidation",
        "migration_type": "Site consolidation",
        "migration_type_value": "site_consolidation",
        "region": "APA",
        "areas": ["GCA", "NEA"],
        "countries": ["China", "South Korea"],
        "area_country_pairs": [
            {"area": "GCA", "country": "China"},
            {"area": "NEA", "country": "South Korea"},
        ],
        "default_location_strategies": ["Shanghai", "Singapore"],
        "custom_location_strategies": [],
        "location_strategy_custom": False,
        "function_name": "Customer Delivery",
        "products": ["General Ocean", "FCL"],
        "proposed_scope": "Consolidate APAC ocean booking and documentation workflows from legacy sites into the regional GSC hub, including SOP alignment and trainer onboarding.",
        "language_dependencies": ["English", "Mandarin Chinese", "Korean"],
        "fte_number": "32",
        "jl2": "10",
        "jl3": "14",
        "jl4": "8",
        "job_level_total": 32,
        "risks": "Integration dependencies with legacy TMS may delay cutover. Key-person risk in Shanghai documentation team.",
    },
    {
        "migration_request_id": "WPM_PRJ_20260620104521",
        "requested_date": "20 Jun 2026, 10:45:21",
        "requestor": "JDOE01",
        "status": "in_review",
        "project_name": "EU Customs Modernization",
        "migration_type": "Process transformation",
        "migration_type_value": "process_transformation",
        "region": "EUR",
        "areas": ["NDC", "SWE"],
        "countries": ["Netherlands", "Sweden"],
        "area_country_pairs": [
            {"area": "NDC", "country": "Netherlands"},
            {"area": "SWE", "country": "Sweden"},
        ],
        "default_location_strategies": ["Rotterdam"],
        "custom_location_strategies": [],
        "location_strategy_custom": False,
        "function_name": "Customer Delivery",
        "products": ["General Customs"],
        "proposed_scope": "Modernize EU customs declaration and compliance processes, migrating to standardized GSC workflows with updated regulatory controls.",
        "language_dependencies": ["English", "Dutch", "German", "Swedish"],
        "fte_number": "18",
        "jl2": "6",
        "jl3": "8",
        "jl4": "4",
        "job_level_total": 18,
        "risks": "Regulatory change windows in Q3 may constrain testing. Cross-border data residency review pending.",
    },
    {
        "migration_request_id": "WPM_PRJ_20260701153008",
        "requested_date": "01 Jul 2026, 15:30:08",
        "requestor": "MKUMAR2",
        "status": "planning",
        "project_name": "IMEA Finance Hub Migration",
        "migration_type": "Functional migration",
        "migration_type_value": "functional_migration",
        "region": "IMEA",
        "areas": ["UAE", "IBS"],
        "countries": ["United Arab Emirates", "India"],
        "area_country_pairs": [
            {"area": "UAE", "country": "United Arab Emirates"},
            {"area": "IBS", "country": "India"},
        ],
        "default_location_strategies": ["Dubai", "Pune"],
        "custom_location_strategies": [],
        "location_strategy_custom": False,
        "function_name": "ATR (Accounting to Reporting)",
        "products": ["General L&S", "General Ocean"],
        "proposed_scope": "Migrate IMEA finance reporting and month-end close activities to the regional hub with harmonized chart-of-accounts mapping.",
        "language_dependencies": ["English", "Arabic", "Hindi"],
        "fte_number": "24",
        "jl2": "8",
        "jl3": "10",
        "jl4": "6",
        "job_level_total": 24,
        "risks": "Parallel run period overlaps with year-end close. ERP interface stability required before wave 2.",
    },
    {
        "migration_request_id": "WPM_PRJ_20260705110947",
        "requested_date": "05 Jul 2026, 11:09:47",
        "requestor": "SCHEN9",
        "status": "in_progress",
        "project_name": "NAM Air Freight Digitization",
        "migration_type": "Digital enablement",
        "migration_type_value": "digital_enablement",
        "region": "NAM",
        "areas": ["USA", "CAA"],
        "countries": ["United States", "Canada"],
        "area_country_pairs": [
            {"area": "USA", "country": "United States"},
            {"area": "CAA", "country": "Canada"},
        ],
        "default_location_strategies": [],
        "custom_location_strategies": ["Charlotte", "Monterrey"],
        "location_strategy_custom": True,
        "custom_location_strategy_justification": "Customer SLA requires bilingual support coverage across US Eastern and Central time zones not available in default site roster.",
        "custom_approval_file_name": "NAM_Air_Custom_Sites_Approval.pdf",
        "custom_approval_file_size": 245760,
        "custom_approval_file_type": "application/pdf",
        "function_name": "Customer Delivery",
        "products": ["General Air", "Booking Services"],
        "proposed_scope": "Digitize air freight booking, tracking, and exception management for NAM export lanes with automated status notifications.",
        "language_dependencies": ["English", "Spanish", "French"],
        "fte_number": "15",
        "jl2": "5",
        "jl3": "6",
        "jl4": "4",
        "job_level_total": 15,
        "risks": "Carrier API rate limits causing intermittent sync failures. UAT sign-off delayed by two weeks.",
    },
    {
        "migration_request_id": "WPM_PRJ_20260708164233",
        "requested_date": "08 Jul 2026, 16:42:33",
        "requestor": "ARODRIG3",
        "status": "at_risk",
        "project_name": "LAM LCL Consolidation",
        "migration_type": "Site consolidation",
        "migration_type_value": "site_consolidation",
        "region": "LAM",
        "areas": ["ECSA", "WCSA"],
        "countries": ["Brazil", "Chile"],
        "area_country_pairs": [
            {"area": "ECSA", "country": "Brazil"},
            {"area": "WCSA", "country": "Chile"},
        ],
        "default_location_strategies": ["Santos", "Santiago"],
        "custom_location_strategies": [],
        "location_strategy_custom": False,
        "function_name": "OCL - Ocean Fulfilment",
        "products": ["General Ocean", "Ocean LCL"],
        "proposed_scope": "Consolidate LAM LCL documentation and cargo planning into a single nearshore GSC footprint with shared capacity model.",
        "language_dependencies": ["English", "Portuguese", "Spanish"],
        "fte_number": "21",
        "jl2": "7",
        "jl3": "9",
        "jl4": "5",
        "job_level_total": 21,
        "risks": "Port strike contingency may impact Santos volume. Vendor staffing gap in Santiago for Q3 peak season.",
    },
    {
        "migration_request_id": "WPM_PRJ_20260522100715",
        "requested_date": "22 May 2026, 10:07:15",
        "requestor": "PWONG5",
        "status": "completed",
        "project_name": "SEA Warehouse Ops Standardization",
        "migration_type": "Process transformation",
        "migration_type_value": "process_transformation",
        "region": "APA",
        "areas": ["SEA", "Mekong"],
        "countries": ["Singapore", "Vietnam", "Thailand"],
        "area_country_pairs": [
            {"area": "SEA", "country": "Singapore"},
            {"area": "Mekong", "country": "Vietnam"},
            {"area": "Mekong", "country": "Thailand"},
        ],
        "default_location_strategies": ["Singapore", "Ho Chi Minh City"],
        "custom_location_strategies": [],
        "location_strategy_custom": False,
        "function_name": "Customer Delivery",
        "products": ["General Warehouse & Distribution", "SCM"],
        "proposed_scope": "Standardize inbound/outbound warehouse operations across SEA and Mekong with unified WMS procedures and KPI dashboards.",
        "language_dependencies": ["English", "Vietnamese", "Thai", "Malay"],
        "fte_number": "28",
        "jl2": "9",
        "jl3": "12",
        "jl4": "7",
        "job_level_total": 28,
        "risks": "",
    },
    {
        "migration_request_id": "WPM_PRJ_20260710141852",
        "requested_date": "10 Jul 2026, 14:18:52",
        "requestor": "LYL114",
        "status": "new",
        "project_name": "EUR OTC Billing Harmonization",
        "migration_type": "Functional migration",
        "migration_type_value": "functional_migration",
        "region": "EUR",
        "areas": ["UK&I", "CSE"],
        "countries": ["United Kingdom", "Poland"],
        "area_country_pairs": [
            {"area": "UK&I", "country": "United Kingdom"},
            {"area": "CSE", "country": "Poland"},
        ],
        "default_location_strategies": ["Gdansk", "London"],
        "custom_location_strategies": [],
        "location_strategy_custom": False,
        "function_name": "OTC (Order to Cash)",
        "products": ["General L&S", "General Ocean"],
        "proposed_scope": "Harmonize order-to-cash billing cycles and dispute resolution workflows across UK&I and CSE with single invoice template library.",
        "language_dependencies": ["English", "Polish", "German"],
        "fte_number": "12",
        "jl2": "4",
        "jl3": "5",
        "jl4": "3",
        "job_level_total": 12,
        "risks": "Legacy billing system decommission timeline not yet confirmed by IT.",
    },
    {
        "migration_request_id": "WPM_PRJ_20260712103000",
        "requested_date": "12 Jul 2026, 10:30:00",
        "requestor": "HNIELSEN",
        "status": "planning",
        "project_name": "Nordic Sales Ops Enablement",
        "migration_type": "Digital enablement",
        "migration_type_value": "digital_enablement",
        "region": "EUR",
        "areas": ["NDC"],
        "countries": ["Denmark", "Norway"],
        "area_country_pairs": [
            {"area": "NDC", "country": "Denmark"},
            {"area": "NDC", "country": "Norway"},
        ],
        "default_location_strategies": ["Copenhagen"],
        "custom_location_strategies": [],
        "location_strategy_custom": False,
        "function_name": "Sales Operations & Enablement",
        "products": ["General Lead Logistics", "General Ocean"],
        "proposed_scope": "Enable Nordic sales operations with centralized quoting tools, pipeline reporting, and CRM-to-GSC handoff automation.",
        "language_dependencies": ["English", "Danish", "Norwegian", "Swedish"],
        "fte_number": "9",
        "jl2": "3",
        "jl3": "4",
        "jl4": "2",
        "job_level_total": 9,
        "risks": "CRM data quality issues in legacy Nordics accounts may slow migration wave 1.",
    },
    {
        "migration_request_id": "WPM_PRJ_20260703142018",
        "requested_date": "03 Jul 2026, 14:20:18",
        "requestor": "TPATEL7",
        "status": "in_progress",
        "project_name": "India PTP Procurement Hub",
        "migration_type": "Functional migration",
        "migration_type_value": "functional_migration",
        "region": "IMEA",
        "areas": ["IBS", "PAK"],
        "countries": ["India", "Pakistan"],
        "area_country_pairs": [
            {"area": "IBS", "country": "India"},
            {"area": "PAK", "country": "Pakistan"},
        ],
        "default_location_strategies": ["Pune", "Karachi"],
        "custom_location_strategies": [],
        "location_strategy_custom": False,
        "function_name": "PTP (Procure to Pay)",
        "products": ["General L&S", "General Ocean"],
        "proposed_scope": "Centralize procure-to-pay invoice processing and vendor onboarding for IMEA into a shared offshore hub.",
        "language_dependencies": ["English", "Hindi", "Urdu"],
        "fte_number": "26",
        "jl2": "8",
        "jl3": "11",
        "jl4": "7",
        "job_level_total": 26,
        "risks": "Vendor master data cleanup incomplete for Pakistan entity.",
    },
    {
        "migration_request_id": "WPM_PRJ_20260628165542",
        "requested_date": "28 Jun 2026, 16:55:42",
        "requestor": "LFERREIRA",
        "status": "in_review",
        "project_name": "Brazil Last Mile Optimization",
        "migration_type": "Process transformation",
        "migration_type_value": "process_transformation",
        "region": "LAM",
        "areas": ["ECSA"],
        "countries": ["Brazil"],
        "area_country_pairs": [{"area": "ECSA", "country": "Brazil"}],
        "default_location_strategies": ["Santos"],
        "custom_location_strategies": [],
        "location_strategy_custom": False,
        "function_name": "Customer Delivery",
        "products": ["Last Mile", "General INLAND"],
        "proposed_scope": "Redesign last-mile delivery coordination and exception handling for Brazilian domestic lanes.",
        "language_dependencies": ["English", "Portuguese"],
        "fte_number": "14",
        "jl2": "5",
        "jl3": "6",
        "jl4": "3",
        "job_level_total": 14,
        "risks": "Local carrier contract renegotiation may shift scope boundaries.",
    },
    {
        "migration_request_id": "WPM_PRJ_20260706110833",
        "requested_date": "06 Jul 2026, 11:08:33",
        "requestor": "YKIM88",
        "status": "new",
        "project_name": "Korea Cold Chain Migration",
        "migration_type": "Site consolidation",
        "migration_type_value": "site_consolidation",
        "region": "APA",
        "areas": ["NEA"],
        "countries": ["South Korea"],
        "area_country_pairs": [{"area": "NEA", "country": "South Korea"}],
        "default_location_strategies": ["Busan"],
        "custom_location_strategies": [],
        "location_strategy_custom": False,
        "function_name": "Customer Delivery",
        "products": ["General Cold Chain"],
        "proposed_scope": "Consolidate Korea reefer booking and temperature monitoring workflows into NEA GSC with updated SOP library.",
        "language_dependencies": ["English", "Korean"],
        "fte_number": "11",
        "jl2": "4",
        "jl3": "5",
        "jl4": "2",
        "job_level_total": 11,
        "risks": "",
    },
    {
        "migration_request_id": "WPM_PRJ_20260530120955",
        "requested_date": "30 May 2026, 12:09:55",
        "requestor": "MGARCIA4",
        "status": "completed",
        "project_name": "Mexico Intermodal Hub Setup",
        "migration_type": "Site consolidation",
        "migration_type_value": "site_consolidation",
        "region": "NAM",
        "areas": ["MEX"],
        "countries": ["Mexico"],
        "area_country_pairs": [{"area": "MEX", "country": "Mexico"}],
        "default_location_strategies": ["Monterrey"],
        "custom_location_strategies": [],
        "location_strategy_custom": False,
        "function_name": "Customer Delivery",
        "products": ["Intermodal - Multicarrier", "Middle Mile"],
        "proposed_scope": "Establish Monterrey as NAM nearshore hub for intermodal planning and carrier allocation.",
        "language_dependencies": ["English", "Spanish"],
        "fte_number": "19",
        "jl2": "6",
        "jl3": "8",
        "jl4": "5",
        "job_level_total": 19,
        "risks": "",
    },
    {
        "migration_request_id": "WPM_PRJ_20260709174520",
        "requested_date": "09 Jul 2026, 17:45:20",
        "requestor": "ABAKR12",
        "status": "at_risk",
        "project_name": "Egypt & East Africa Trade Lane",
        "migration_type": "Functional migration",
        "migration_type_value": "functional_migration",
        "region": "IMEA",
        "areas": ["EAA", "WAF"],
        "countries": ["Egypt", "Kenya", "Nigeria"],
        "area_country_pairs": [
            {"area": "EAA", "country": "Egypt"},
            {"area": "EAA", "country": "Kenya"},
            {"area": "WAF", "country": "Nigeria"},
        ],
        "default_location_strategies": ["Cairo"],
        "custom_location_strategies": ["Lagos", "Nairobi"],
        "location_strategy_custom": True,
        "custom_location_strategy_justification": "Multi-country trade lane requires distributed coverage for local customs liaison in Lagos and Nairobi.",
        "custom_approval_file_name": "IMEA_TradeLane_SiteApproval.docx",
        "custom_approval_file_size": 184320,
        "custom_approval_file_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "function_name": "Customer Delivery",
        "products": ["General Ocean", "General Customs"],
        "proposed_scope": "Migrate Egypt and East Africa ocean documentation and customs filing to a regional operating model.",
        "language_dependencies": ["English", "Arabic", "French"],
        "fte_number": "22",
        "jl2": "7",
        "jl3": "10",
        "jl4": "5",
        "job_level_total": 22,
        "risks": "Political instability affecting Lagos port operations. Customs API downtime in Kenya last month.",
    },
    {
        "migration_request_id": "WPM_PRJ_20260704133011",
        "requested_date": "04 Jul 2026, 13:30:11",
        "requestor": "RSTEWART",
        "status": "planning",
        "project_name": "US Midwest Warehouse Consolidation",
        "migration_type": "Site consolidation",
        "migration_type_value": "site_consolidation",
        "region": "NAM",
        "areas": ["USA"],
        "countries": ["United States"],
        "area_country_pairs": [{"area": "USA", "country": "United States"}],
        "default_location_strategies": ["Chicago", "Dallas"],
        "custom_location_strategies": [],
        "location_strategy_custom": False,
        "function_name": "Customer Delivery",
        "products": ["General Warehouse & Distribution", "Maersk Flow"],
        "proposed_scope": "Merge US Midwest warehouse planning and inventory reconciliation into two anchor GSC sites.",
        "language_dependencies": ["English"],
        "fte_number": "17",
        "jl2": "6",
        "jl3": "7",
        "jl4": "4",
        "job_level_total": 17,
        "risks": "Union consultation required before Chicago headcount transfer.",
    },
    {
        "migration_request_id": "WPM_PRJ_20260618102007",
        "requested_date": "18 Jun 2026, 10:20:07",
        "requestor": "CPETERS",
        "status": "in_progress",
        "project_name": "Germany Business Controlling Rollout",
        "migration_type": "Functional migration",
        "migration_type_value": "functional_migration",
        "region": "EUR",
        "areas": ["EME", "NEC"],
        "countries": ["Germany", "Austria"],
        "area_country_pairs": [
            {"area": "EME", "country": "Germany"},
            {"area": "NEC", "country": "Austria"},
        ],
        "default_location_strategies": ["Hamburg"],
        "custom_location_strategies": [],
        "location_strategy_custom": False,
        "function_name": "Business Controlling",
        "products": ["General L&S", "General Ocean"],
        "proposed_scope": "Roll out standardized management reporting and cost allocation for DACH business controlling teams.",
        "language_dependencies": ["English", "German"],
        "fte_number": "13",
        "jl2": "4",
        "jl3": "6",
        "jl4": "3",
        "job_level_total": 13,
        "risks": "SAP BW extract performance degrading during month-end parallel run.",
    },
    {
        "migration_request_id": "WPM_PRJ_20260711154539",
        "requested_date": "11 Jul 2026, 15:45:39",
        "requestor": "NTANAKA",
        "status": "new",
        "project_name": "Japan Customer Experience uplift",
        "migration_type": "Digital enablement",
        "migration_type_value": "digital_enablement",
        "region": "APA",
        "areas": ["NEA", "Oceania"],
        "countries": ["Japan", "Australia"],
        "area_country_pairs": [
            {"area": "NEA", "country": "Japan"},
            {"area": "Oceania", "country": "Australia"},
        ],
        "default_location_strategies": ["Tokyo", "Sydney"],
        "custom_location_strategies": [],
        "location_strategy_custom": False,
        "function_name": "Customer Experience",
        "products": ["General Ocean"],
        "proposed_scope": "Deploy unified customer inquiry handling and NPS feedback loops across Japan and Oceania export desks.",
        "language_dependencies": ["English", "Japanese"],
        "fte_number": "8",
        "jl2": "3",
        "jl3": "3",
        "jl4": "2",
        "job_level_total": 8,
        "risks": "",
    },
    {
        "migration_request_id": "WPM_PRJ_20260625113844",
        "requested_date": "25 Jun 2026, 11:38:44",
        "requestor": "VSHARMA6",
        "status": "in_review",
        "project_name": "South Asia LCL Documentation",
        "migration_type": "Process transformation",
        "migration_type_value": "process_transformation",
        "region": "IMEA",
        "areas": ["SAA", "PAK"],
        "countries": ["India", "Bangladesh", "Sri Lanka"],
        "area_country_pairs": [
            {"area": "SAA", "country": "India"},
            {"area": "SAA", "country": "Bangladesh"},
            {"area": "SAA", "country": "Sri Lanka"},
        ],
        "default_location_strategies": ["Chennai", "Colombo"],
        "custom_location_strategies": [],
        "location_strategy_custom": False,
        "function_name": "Customer Delivery",
        "products": ["General LCL", "Ocean LCL"],
        "proposed_scope": "Transform South Asia LCL documentation with automated BL issuance and consolidated manifest processing.",
        "language_dependencies": ["English", "Hindi", "Bengali", "Tamil"],
        "fte_number": "20",
        "jl2": "7",
        "jl3": "8",
        "jl4": "5",
        "job_level_total": 20,
        "risks": "Bangladesh public holiday calendar impacts UAT schedule in August.",
    },
    {
        "migration_request_id": "WPM_PRJ_20260707160028",
        "requested_date": "07 Jul 2026, 16:00:28",
        "requestor": "JMARTINZ",
        "status": "planning",
        "project_name": "Chile WCSA E-Commerce Enablement",
        "migration_type": "Digital enablement",
        "migration_type_value": "digital_enablement",
        "region": "LAM",
        "areas": ["WCSA"],
        "countries": ["Chile", "Peru"],
        "area_country_pairs": [
            {"area": "WCSA", "country": "Chile"},
            {"area": "WCSA", "country": "Peru"},
        ],
        "default_location_strategies": ["Santiago", "Lima"],
        "custom_location_strategies": [],
        "location_strategy_custom": False,
        "function_name": "Customer Delivery",
        "products": ["General E-Commerce", "Last Mile"],
        "proposed_scope": "Enable e-commerce parcel handling and returns processing for WCSA cross-border lanes.",
        "language_dependencies": ["English", "Spanish"],
        "fte_number": "10",
        "jl2": "3",
        "jl3": "4",
        "jl4": "3",
        "job_level_total": 10,
        "risks": "Marketplace partner API documentation incomplete for Peru corridor.",
    },
    {
        "migration_request_id": "WPM_PRJ_20260515143000",
        "requested_date": "15 May 2026, 14:30:00",
        "requestor": "EJOHNSON",
        "status": "completed",
        "project_name": "UK&I Lead Logistics Program",
        "migration_type": "Process transformation",
        "migration_type_value": "process_transformation",
        "region": "EUR",
        "areas": ["UK&I"],
        "countries": ["United Kingdom", "Ireland"],
        "area_country_pairs": [
            {"area": "UK&I", "country": "United Kingdom"},
            {"area": "UK&I", "country": "Ireland"},
        ],
        "default_location_strategies": ["London"],
        "custom_location_strategies": [],
        "location_strategy_custom": False,
        "function_name": "Customer Program Management",
        "products": ["General Lead Logistics"],
        "proposed_scope": "Deliver end-to-end lead logistics program management for UK&I strategic accounts with unified governance model.",
        "language_dependencies": ["English"],
        "fte_number": "16",
        "jl2": "5",
        "jl3": "7",
        "jl4": "4",
        "job_level_total": 16,
        "risks": "",
    },
    {
        "migration_request_id": "WPM_PRJ_20260713110045",
        "requested_date": "13 Jul 2026, 11:00:45",
        "requestor": "LYL114",
        "status": "new",
        "project_name": "Philippines SCM Orchestration Pilot",
        "migration_type": "Digital enablement",
        "migration_type_value": "digital_enablement",
        "region": "APA",
        "areas": ["SEA"],
        "countries": ["Philippines"],
        "area_country_pairs": [{"area": "SEA", "country": "Philippines"}],
        "default_location_strategies": ["Manila"],
        "custom_location_strategies": [],
        "location_strategy_custom": False,
        "function_name": "Customer Delivery",
        "products": ["SCM", "Supply Chain Orchestrator"],
        "proposed_scope": "Pilot supply chain orchestration control tower for Philippines export customers with exception-based management.",
        "language_dependencies": ["English", "Filipino (Tagalog)"],
        "fte_number": "7",
        "jl2": "2",
        "jl3": "3",
        "jl4": "2",
        "job_level_total": 7,
        "risks": "Pilot scope limited to two anchor accounts; expansion criteria not yet defined.",
    },
]


class Command(BaseCommand):
    help = "Seed migration_intake_submission with sample project data."

    def add_arguments(self, parser):
        parser.add_argument(
            "--clear",
            action="store_true",
            help="Delete all existing submissions before seeding.",
        )

    def handle(self, *args, **options):
        if options["clear"]:
            deleted, _ = MigrationIntakeSubmission.objects.all().delete()
            self.stdout.write(self.style.WARNING(f"Cleared {deleted} existing row(s)."))

        created = 0
        updated = 0

        for payload in SAMPLE_SUBMISSIONS:
            request_id = payload["migration_request_id"]
            _, was_created = MigrationIntakeSubmission.objects.update_or_create(
                migration_request_id=request_id,
                defaults=payload,
            )
            if was_created:
                created += 1
            else:
                updated += 1

        total = MigrationIntakeSubmission.objects.count()
        self.stdout.write(
            self.style.SUCCESS(
                f"Seed complete: {created} created, {updated} updated. "
                f"Total rows in migration_intake_submission: {total}."
            )
        )
