"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import ssl
import certifi
from dotenv import load_dotenv
from pathlib import Path

# Patch urllib's default SSL context to use certifi's CA bundle.
# This is needed because python-http-client (used by SendGrid) uses urllib,
# which otherwise fails against the corporate proxy's GoDaddy-signed certs.
_orig_create_default_context = ssl.create_default_context

def _patched_create_default_context(purpose=ssl.Purpose.SERVER_AUTH, **kwargs):
    kwargs.setdefault("cafile", certifi.where())
    return _orig_create_default_context(purpose, **kwargs)

ssl.create_default_context = _patched_create_default_context
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR.parent / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-_h_7o7_s)$n&q%j%*n$92zh13#uctf1$aw$6b3e#nfqm%n6nbs",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in ("1", "true", "yes")

# Comma-separated hosts, e.g. localhost,127.0.0.1,SCRBAEXDEFRM217
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get(
        "DJANGO_ALLOWED_HOSTS",
        "localhost,127.0.0.1,SCRBAEXDEFRM217,10.176.115.28,*",
    ).split(",")
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Default: local SQLite.
# SQL Server: set DJANGO_DB_ENGINE=mssql (uses Windows Trusted Connection).
# Optional overrides: DJANGO_DB_NAME, DJANGO_DB_HOST, DJANGO_DB_PORT, DJANGO_DB_DRIVER

_DB_ENGINE = os.environ.get("DJANGO_DB_ENGINE", "sqlite").strip().lower()

if _DB_ENGINE in ("mssql", "sqlserver"):
    _db_user = os.environ.get("DJANGO_DB_USER", "").strip()
    _db_password = os.environ.get("DJANGO_DB_PASSWORD", "")
    _db_config = {
        "ENGINE": "mssql",
        "NAME": os.environ.get("DJANGO_DB_NAME", "WPM Project"),
        "HOST": os.environ.get("DJANGO_DB_HOST", "SCRBAEXDEFRM218"),
        "PORT": os.environ.get("DJANGO_DB_PORT", "1433"),
        "OPTIONS": {
            "driver": os.environ.get(
                "DJANGO_DB_DRIVER", "ODBC Driver 17 for SQL Server"
            ),
            "extra_params": os.environ.get(
                "DJANGO_DB_EXTRA_PARAMS",
                "Trusted_Connection=yes;Encrypt=yes;TrustServerCertificate=yes;",
            ),
        },
    }
    # If USER is set, switch to SQL authentication (disable Trusted_Connection).
    if _db_user:
        _db_config["USER"] = _db_user
        _db_config["PASSWORD"] = _db_password
        _db_config["OPTIONS"]["extra_params"] = os.environ.get(
            "DJANGO_DB_EXTRA_PARAMS",
            "Encrypt=yes;TrustServerCertificate=yes;",
        )
    DATABASES = {"default": _db_config}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS — 开发端口 + 同机 Apache 部署入口
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "DJANGO_CORS_ORIGINS",
        "http://localhost:3001,http://127.0.0.1:3001,http://localhost,http://127.0.0.1,http://10.176.115.28,http://SCRBAEXDEFRM217",
    ).split(",")
    if origin.strip()
]

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
}

# Email — SendGrid HTTP API (avoids SMTP port 25/587 corporate firewall blocks).
# Routes through corporate proxy at 10.0.11.1:9400 for outbound HTTPS.
EMAIL_BACKEND = os.environ.get(
    "DJANGO_EMAIL_BACKEND", "sendgrid_backend.SendgridBackend"
)
SENDGRID_API_KEY = os.environ.get(
    "DJANGO_SENDGRID_API_KEY", ""
)
SENDGRID_SANDBOX_MODE_IN_DEBUG = False

# Corporate proxy for outbound HTTPS (SendGrid API goes through this).
_PROXY = os.environ.get("DJANGO_HTTPS_PROXY", "http://10.0.11.1:9400")
if _PROXY:
    os.environ.setdefault("HTTPS_PROXY", _PROXY)
    os.environ.setdefault("https_proxy", _PROXY)

# Sender must be a verified sender in SendGrid.
DEFAULT_FROM_EMAIL = os.environ.get("DJANGO_DEFAULT_FROM_EMAIL", "noreply@maersk.com")
MIGRATION_INTAKE_NOTIFY_TO = [
    email.strip()
    for email in os.environ.get("DJANGO_MIGRATION_INTAKE_NOTIFY_TO", "").split(",")
    if email.strip()
]
